#ifndef 10_12_REPLACE_CONSTRUCTOR_WITH_FACTORY_METHOD_H
#define 10_12_REPLACE_CONSTRUCTOR_WITH_FACTORY_METHOD_H

// 适用情景：


// 原始版本


// 新版本


#endif // 10_12_REPLACE_CONSTRUCTOR_WITH_FACTORY_METHOD_H
