#ifndef 9_5_REPLACE_NESTED_CONDITIONAL_WITH_GUARD_CLAUSES_H
#define 9_5_REPLACE_NESTED_CONDITIONAL_WITH_GUARD_CLAUSES_H

// 适用情景：


// 原版本


// 新版本

#endif // 9_5_REPLACE_NESTED_CONDITIONAL_WITH_GUARD_CLAUSES_H
